### ISSUE TITLE
[Security] GitHub Actions

### ISSUE THREAD

**Issue by Ry0taK** [aevea/release-notary#257]
Hello aevea team!
I'm a security researcher who is working on OSS security.

While doing a research related to supply chain attack, I noticed that some repositories are vulnerable to repository hijacking. (This issue has been mitigated by me and GitHub.)
Since the root cause of this issue hasn't been fixed, I'd like to let you know what you should do.

In [README.md](https://github.com/aevea/release-notary/blob/4038392236d1262df4ccf414636ae783d628e369/README.md), there is an example that uses `commitsar-app/release-notary` to use this action.
However, as this repository has been renamed to `aevea/release-notary`, this example should be updated.
While it's working properly as there is a feature named [Repository redirects](https://github.blog/2013-05-16-repository-redirects-are-here/), `commitsar-app` could be claimed by anyone, and allows repository hijacking once someone published new release. (I already claimed this username, so it can't be abused anymore.)
Since [yay](https://github.com/Jguer/yay) has been affected by this issue, I opened the issue on yay: https://github.com/Jguer/yay/issues/1468
(For more context, I've written an article that describes this problem (It's written in Japanese): https://blog.ryotak.me/post/github-actions-supplychain/)

Best Regards,
RyotaK

**Comment by fallion** [comment]
@Ry0taK thanks for this find!

The README really needs updates. I will try to mitigate this today.

**Comment by fallion** [comment]
@Ry0taK this is now merged. I'll let you close it if all is ok :)

**Comment by Ry0taK** [comment]
@fallion I've confirmed that outdated username has been removed from README.md, thank you so much for fixing it ;)
